/*
 * This source code has been generated by blanco Framework.
 */
/**
 * The interface definition of a list that gets instances from API argument string.
 *
 * @author blanco Framework
 */
export interface SampleApiListInterface {
  [i: string]: any;
}
