/*
 * This source code has been generated by blanco Framework.
 */
import { SampleMethodTest } from "@/samples/api/SampleMethodTest";
import { ApiSample } from "@/samples/api/ApiSample";
import { LoginSample } from "@/samples/api/LoginSample";
import { SampleApiListInterface } from "./SampleApiListInterface";

/**
 * A class that holds a list of instances to be obtained from API argument string.
 */
export class SampleApiList {
  /**
   * A list of instances to be obtained from API argument string.
   */
  static constructors: SampleApiListInterface = {
    ApiSample: ApiSample,
    SampleMethodTest: SampleMethodTest,
    LoginSample: LoginSample
  };
}
