/*
 * This source code has been generated by blanco Framework.
 */
import { ApiPostTelegram } from "%/blanco/restgenerator/valueobject/ApiPostTelegram";

/**
 * blancoRestのサンプルAPIの応答電文です。
 */
export class LoginSamplePostResponse extends ApiPostTelegram {
    /**
     * ログインに成功した場合はtoken文字列が返されます
     *
     * 規定値   [&quot;&quot;]
     */
    private fToken: string = "";

    /**
     * フィールド [token]のセッターメソッド
     *
     * 項目の型 [ログインに成功した場合はtoken文字列が返されます]
     *
     * @param argToken フィールド[token]に格納したい値
     */
    set token(argToken: string) {
        this.fToken = argToken;
    }

    /**
     * フィールド[token]のゲッターメソッド
     *
     * 項目の型 [ログインに成功した場合はtoken文字列が返されます]
     * 規定値   [&quot;&quot;]
     *
     * @return フィールド[token]に格納されている値
     */
    get token(): string {
        return this.fToken;
    }

    /**
     * フィールド[token]のゲッターメソッド
     *
     * 項目の型 [string]
     * ログインに成功した場合はtoken文字列が返されます
     *
     * @return フィールド[token]の型名文字列
     */
    static typeToken(): string | undefined {
        return "string";
    }

    /**
     * Returns the name of this telegram class as a string.
     *
     * @return The class name of this telegram.
     */
    get telegramId(): string {
        return "LoginSamplePostResponse";
    }

    /**
     * Gets the properties to be written to JSON from this telegram.
     *
     * @return An object returned by toJSON
     */
    toJSON(): any {
        return {
            token: this.token
        };
    }
}
