/*
 * This source code has been generated by blanco Framework.
 */
import { ApiGetTelegram } from "%/blanco/restgenerator/valueobject/ApiGetTelegram";

/**
 * GETメソッドの応答電文
 */
export class SampleMethodTestGetResponse extends ApiGetTelegram {
    /**
     * Returns the name of this telegram class as a string.
     *
     * @return The class name of this telegram.
     */
    get telegramId(): string {
        return "SampleMethodTestGetResponse";
    }
}
