/*
 * This source code has been generated by blanco Framework.
 */
import { ApiPutTelegram } from "%/blanco/restgenerator/valueobject/ApiPutTelegram";

/**
 * PUTメソッドの応答電文
 */
export class SampleMethodTestPutResponse extends ApiPutTelegram {
    /**
     * Returns the name of this telegram class as a string.
     *
     * @return The class name of this telegram.
     */
    get telegramId(): string {
        return "SampleMethodTestPutResponse";
    }
}
