/*
 * This source code has been generated by blanco Framework.
 */
import { ApiDeleteTelegram } from "%/blanco/restgenerator/valueobject/ApiDeleteTelegram";

/**
 * DELETEメソッドの応答電文
 */
export class SampleMethodTestDeleteResponse extends ApiDeleteTelegram {
    /**
     * Returns the name of this telegram class as a string.
     *
     * @return The class name of this telegram.
     */
    get telegramId(): string {
        return "SampleMethodTestDeleteResponse";
    }
}
