/*
 * This source code has been generated by blanco Framework.
 */
import { ApiPostTelegram } from "%/blanco/restgenerator/valueobject/ApiPostTelegram";

/**
 * POSTメソッドの応答電文
 */
export class SampleMethodTestPostResponse extends ApiPostTelegram {
    /**
     * Returns the name of this telegram class as a string.
     *
     * @return The class name of this telegram.
     */
    get telegramId(): string {
        return "SampleMethodTestPostResponse";
    }
}
