/*
 * This source code has been generated by blanco Framework.
 */
import { ApiGetTelegram } from "%/blanco/restgenerator/valueobject/ApiGetTelegram";

/**
 * blancoRestのサンプルAPIの応答電文です。
 */
export class ApiPlainSampleGetResponse extends ApiGetTelegram {
    /**
     * データ
     *
     * 規定値   [new Array&lt;string&gt;()]
     */
    private fData: Array<string> = new Array<string>();

    /**
     * フィールド [data]のセッターメソッド
     *
     * 項目の型 [データ]
     *
     * @param argData フィールド[data]に格納したい値
     */
    set data(argData: Array<string>) {
        this.fData = argData;
    }

    /**
     * フィールド[data]のゲッターメソッド
     *
     * 項目の型 [データ]
     * 規定値   [new Array&lt;string&gt;()]
     *
     * @return フィールド[data]に格納されている値
     */
    get data(): Array<string> {
        return this.fData;
    }

    /**
     * フィールド[data]のゲッターメソッド
     *
     * 項目の型 [Array]
     * データ
     *
     * @return フィールド[data]の型名文字列
     */
    static typeData(): string | undefined {
        return "Array";
    }

    /**
     * フィールド[data]のゲッターメソッド
     *
     * 項目の型 [string]
     * データ
     *
     * @return フィールド[data]の型名文字列
     */
    static genericData(): string | undefined {
        return "string";
    }

    /**
     * Returns the name of this telegram class as a string.
     *
     * @return The class name of this telegram.
     */
    get telegramId(): string {
        return "ApiPlainSampleGetResponse";
    }

    /**
     * Returns the kind of this telegram as a string.
     *
     * @return The kind of this telegram.
     */
    get telegramType(): string {
        return "Output";
    }

    /**
     * Returns the method of this telegram as a string.
     *
     * @return The method of this telegram.
     */
    get telegramMethod(): string {
        return "GET";
    }

    /**
     * Gets the properties to be written to JSON from this telegram.
     *
     * @return An object returned by toJSON
     */
    toJSON(): any {
        return {
            data: this.data
        };
    }
}
