/*
 * This source code has been generated by blanco Framework.
 */
import { ApiDeleteTelegram } from "%/blanco/restgenerator/valueobject/ApiDeleteTelegram";

/**
 * 共通エラーResponseを定義するためのダミーAPIの要求電文です。
 */
export class ApiPlainCommonDeleteRequest extends ApiDeleteTelegram {
    /**
     * 規定値   [null]
     */
    private _additionalPath: string | undefined = undefined;

    /**
     * Returns the name of this telegram class as a string.
     *
     * @return The class name of this telegram.
     */
    get telegramId(): string {
        return "ApiPlainCommonDeleteRequest";
    }

    /**
     * Returns the kind of this telegram as a string.
     *
     * @return The kind of this telegram.
     */
    get telegramType(): string {
        return "Input";
    }

    /**
     * Returns the method of this telegram as a string.
     *
     * @return The method of this telegram.
     */
    get telegramMethod(): string {
        return "DELETE";
    }

    /**
     * フィールド [_additionalPath]のセッターメソッド
     *
     * 項目の型 [string | undefined]
     *
     * @param argAdditionalPath フィールド[_additionalPath]に格納したい値
     */
    set additionalPath(argAdditionalPath: string | undefined) {
        this._additionalPath = argAdditionalPath;
    }

    /**
     * フィールド[_additionalPath]のゲッターメソッド
     *
     * 項目の型 [string|undefined]
     *
     * @return フィールド[_additionalPath]に格納されている値
     */
    get additionalPath(): string | undefined {
        return this._additionalPath;
    }

    /**
     * Get the path parameters from this telegram.
     *
     * @return A string returned by getPathParams
     */
    getPathParams(): string | undefined {
        return undefined;
    }

    /**
     * Get the query parameters from this telegram.
     *
     * @return A string returned by getQueryParams
     */
    getQueryParams(): any {
        return undefined;
    }
}
